'use client';
import '@/styles/index.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import EmptyLayout from '@/containers/layouts/EmptyLayout';
import { ReduxProvider, ThemeRegistry } from '@/providers';
import Popups from '@/containers/Popups';
import '@/modules/translations';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

function RootLayout({
    children,
    ...props
}: {
    children: React.ReactNode;
    params: {
        [key: string]: string | string[] | undefined;
    };
}) {
    return <EmptyLayout params={{ ...props?.params }}>{children}</EmptyLayout>;
}

export default RootLayout;
