export const DATE_TIME_FORMAT = 'DD.MM.YYYY HH:mm';
export const DATE_FORMAT = 'DD.MM.YYYY';
export const TIME_FORMAT = 'HH:mm';
export const TIME_FORMAT_FROM_SERVER = 'H:m';
export const DATE_FORMAT_FROM_SERVER = 'YYYY-MM-DD';
export const DATE_FORMAT_TO_SERVER = 'YYYY-MM-DD';
export const DATEPICKER_TITLE_FORMAT = 'MMMM YYYY';
export const DATE_TIME_FORMAT_FROM_SERVER = `${DATE_FORMAT_FROM_SERVER} ${TIME_FORMAT_FROM_SERVER}`;
